Feat/mini challenge 4
PedroEdu6786/react-certification-2021 pull request #7
Opened 2021-08-14 16:54 UTC by PedroEdu6786

### PR Summarize
- Add ThemeContentProvider for handling UI theme state
- Add VideosProvider for handling videos state
- Add test cases for hooks, state reducers
- Add homepage, header and previewRelated list components tests

### Test coverage
![image](https://user-images.githubusercontent.com/50753661/129453597-f15087c8-18a4-483b-8ee3-432d5cf20b08.png)

2021-08-19 21:31 UTC, cehawz requested changes
Creo que deberias de renombrar los archivos de VideoProvider de la siguiente manera:

- `VideoProvider.jsx` -> `VideoProvider.js`
- `videosReducer.js` -> `VideoProvider.reducer.js`
- `videoTypes.js` -> `VideoProvider.types.js`

Crear nuevo archivo para definir actions: 

- `VideosProvider.actions.js`

En general lo veo bastante bien.

Hay algunos test que fallan:

![image](https://user-images.githubusercontent.com/77181879/130146915-5991068f-2440-4099-b0ea-d6e4d1557fff.png)

2021-08-19 21:31 UTC, cehawz commented on src/components/Header/Header.component.jsx
> +            {theme.theme === 'light' ? (
Esta linea necesita unit test.

2021-08-19 21:31 UTC, cehawz commented on src/pages/Home/Home.page.jsx
> +    </BodyContainer>
Falta un unit test para el render de `PreviewList` y `Heading`

2021-08-19 21:31 UTC, cehawz commented on src/utils/helpers.js
> +// youtube api axios config
Esto podria estar en un archivo usado exclusivamente para el consumo de servicios del API de YTB.

2021-08-19 21:31 UTC, cehawz commented on src/pages/Home/Home.page.jsx
> +  const { globalState } = useContext(VideosContext);
Este fetch Videos deberia ser un action. Con la implementación del state management necesitas consultar el API desde los actions.

2021-08-19 21:32 UTC, cehawz commented
Veo bastante bien tu codigo, solo te hice unas recomendaciones. Me avisas para darle otro review.

2021-08-20 20:02 UTC, PedroEdu6786 commented on src/components/Header/Header.component.jsx
> +            {theme.theme === 'light' ? (
Hay un test que prueba el cambio de iconos para probar la condición

2021-08-20 20:26 UTC, PedroEdu6786 commented on src/pages/Home/Home.page.jsx
> +    </BodyContainer>
`PreviewList` es testeado en "loads videos from api" con el data-testid "previewList"

2021-08-20 20:50 UTC, PedroEdu6786 commented on src/pages/Home/Home.page.jsx
> +  const { globalState } = useContext(VideosContext);
No estoy seguro de como llevar ese cambio a cabo, ya que el error y loading state se encuentran en useYoutubeApi hook, y estos states son modificados dentro de la función `fetchVideos` y los hooks solamente pueden ser utilizados en functional react components

2021-08-20 21:02 UTC, PedroEdu6786 commented
@cehawz Parece ser que le error de testing tiene que ver más con codesandbox que con mi código, al parecer hay errores al utilizar jest.mock() y por eso dentro de codesandbox falla mi mock de youtubeClient, sin embargo ya probé en 2 distintos ordenadores de forma local y no pareec repetirse el error que aparece en codesandbox

2021-08-20 21:15 UTC, PedroEdu6786 commented on src/utils/helpers.js
> +// youtube api axios config
No me quedo claro esta parte

2021-08-25 14:40 UTC, cehawz approved these changes

2021-08-25 14:43 UTC, merged